version: '3'

services:
  reactapp:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: reactapp
    ports:
      - 3000:3000
    networks:
      - interna
  nodejsapp:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - IMAGE_VERSION=non_serve
    image: nodejsapp
#    image: vic/debian.iptables.ifconfig
    environment:
      - MIAVAR=non_serve__solo_come_esempio
    ports:
      - 3000:3000
    networks:
      - interna
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
      args:
        - IMAGE_VERSION=non_serve
    image: mymongo
    ports:
      - 27017:27017
    networks:
      - interna
#    volumes:
#      - mydata:/data

networks:
  interna:
    driver: bridge
    driver_opts:
       com.docker.network.bridge.name: "brinterna" 
#      com.docker.network.enable_ipv6: "false"
#volumes:
#  mydata:

